version: '3'

tasks:
  test:
    cmds:
      - go test -v . --timeout 30s
    silent: true
  fmt:
    cmds:
      - go fmt .
    silent: true
  cov:
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out
    silent: true