name: Hoconenv CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Hoconenv
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Format
        run: go fmt .

      - name: Test
        run: go test -v .

      - name: Code coverage
        run: go test -coverprofile=coverage.out